### ISSUE TITLE
Bug: Invalid warning about invalid email

### ISSUE THREAD

**Issue by fraythe** [hexlet-codebattle/codebattle#1969]
### Summary

Warning 'Can't contain special symbols'  instead of 'Invalid email'

### Reproduction steps

```bash
1. Open the main page of the site
2. Click on 'sign up'
3. Enter the nickname
4. Enter email 'joohndee@mail.r'
5. Enter the password
6. Repeat the password
```

### Expected result

Warning 'Invalid email'

### Actual result

Warning 'Can't contain special symbols'

### Current version

8a20565

### Browsers

Chrome

### OS

Mac

**Comment by Andrey-khb** [comment]
Warning 'Can't contain special symbols' instead of 'Invalid email'

Google Chrome, Version 128.0.6613.114, (64 bit),  Win 11 Pro
CodeBattle (Current version: 8a20565)

Reproduction steps
    Nickname = test_Cbattle
    Email = khaba@yan.r
    Password = 123456
    Password Confirmation = 123456

Actual result = Can't contain special symbols

![bug1](https://github.com/user-attachments/assets/a768c440-ea0d-4e45-99f9-0dbae3862247)

**Comment by kalaratri** [comment]
![баг](https://github.com/user-attachments/assets/0262b631-2595-43e2-8a27-b987832ee97f)
summary:
Warning "Can't contain special symbols" instead of "Invalid email"

environment:
OC Windows 10 Pro
Google Chrome 130.0.6723.119

steps-to-reproduce:

Open the main page
Enter Nickname
Enter email "testemail@mail.r"
Enter password
Repeat password

actual-result:
Warning "Can't contain special symbols"

**Comment by ReDBrother** [comment]
It's very common message and doesn't help much
